- name: cart configuration
  hosts: cart
  become: true
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "roboshop system cart"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent    

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory   

  - name: delete cart zip file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent    

  - name: download cart code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: unarchive code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy cart service
    ansible.builtin.template:
      src: cart.service.j2
      dest: /etc/systemd/system/cart.service   


  - name: start cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes                                    
