[mongodb]
mongodb.ramireddy.co.in

[catalogue]
catalogue.ramireddy.co.in

[redis]
redis.ramireddy.co.in

[user]
user.ramireddy.co.in

[cart]
cart.ramireddy.co.in

[mysql]
mysql.ramireddy.co.in

[shipping]
shipping.ramireddy.co.in

[rabbitmq]
rabbitmq.ramireddy.co.in

[payment]
payment.ramireddy.co.in

[dispatch]
dispatch.ramireddy.co.in

[frontend]
frontend.ramireddy.co.in

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb.ramireddy.co.in
CATALOGUE_HOST=catalogue.ramireddy.co.in
REDIS_HOST=redis.ramireddy.co.in
USER_HOST=user.ramireddy.co.in
CART_HOST=cart.ramireddy.co.in
MYSQL_HOST=mysql.ramireddy.co.in
SHIPPING_HOST=shipping.ramireddy.co.in
RABBITMQ_HOST=rabbitmq.ramireddy.co.in
PAYMENT_HOST=payment.ramireddy.co.in
