- name: create ec2 and route 53 records
  hosts: localhost
  connection: local
  vars_files:
  - variables.yml
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group }}"
      image_id: "{{ image_id }}"
      name: "{{ item }}"
      wait: false
      tags:
        Project: "{{ Project }}"
        Environment: "{{ Environment }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create" 

  - name: create route 53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongodb.ramireddy.co.in
      type: A
      ttl: 7200
      value: "{{ item.instances[0].private_ip_address }}"
      wait: false
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: action == "create" 

  - name: create route 53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop.{{ domain_name }}" # roboshop.ramireddy.co.in
      type: A
      ttl: 7200
      value: "{{ item.instances[0].public_ip_address }}"
      wait: false
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: # and
    - item.item == "frontend"
    - action == "create"  

  - name: delete route53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}.{{ domain_name }}" # roboshop.ramireddy.co.in
      type: A
      ttl: 7200  
    loop: "{{ instances }}" 
    when: action == "destroy"    

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}"
      wait: false
    loop: "{{ instances }}"
    when: action == "destroy"    
    


